
"     syn keyword pplBuiltinFunction Abs AccruableDays AccrualFactor Acos ActiveRowCount AddAttachment AddEmailAddress AddJavaScript AddKeyListItem AddMetaTag AddOnLoadScript AddStyleSheet AddSystemPauseTimes AddToDate AddToDateTime AddToTime All AllOrNone AllowEmplidChg Amortize Asin Atan
"     syn keyword pplBuiltinFunction BlackScholesCall BlackScholesPut BootstrapYTMs Break BulkDeleteField BulkInsertField BulkModifyPageFieldOrder BulkUpdateIndexes
"     syn keyword pplBuiltinFunction CallAppEngine CancelPubHeaderXmlDoc CancelPubXmlDoc CancelSubXmlDoc ChangeEmailAddress Char CharType ChDir ChDrive CheckMenuItem ChunkText Clean CleanAttachments ClearKeyList ClearSearchDefault ClearSearchEdit Code Codeb CollectGarbage CommitWork CompareLikeFields CompareStrings CompareTextDiff Component ComponentChanged ConfigureClassicPlusComponent ConfigureClassicPlusForWC ConnectorRequest ConnectorRequestURL ContainsCharType ContainsOnlyCharType Continue ConvertChar ConvertCurrency ConvertDatetimeToBase ConvertRate ConvertTimeToBase CopyAttachments CopyFields CopyFromJavaArray CopyRow CopyToJavaArray Cos Cot create CreateAnalyticInstance CreateArray CreateArrayAny CreateArrayRept CreateBreadcrumb CreateDirectory CreateDocument CreateDocumentKey CreateException CreateJavaArray CreateJavaObject CreateJsonBuilder CreateJsonParser CreateMCFIMInfo CreateMessage CreateObject CreateObjectArray CreateProcessRequest CreateRecord CreateRowset CreateRowsetCache CreateSearchRowset CreateSOAPDoc CreateSQL CreateWSDLMessage CreateXmlDoc CreateXmlDocFactory CropImage CubicSpline CurrEffDt CurrEffRowNum CurrEffSeq CurrentLevelNumber CurrentRowNumber
"     syn keyword pplBuiltinFunction Date Date3 DatePart DateTime6 DateTimeToHTTP DateTimeToISO DateTimeToLocalizedString DateTimeToTimeZone DateTimeToUserFormat DateTimeValue DateValue Day Days Days360 Days365 DBCSTrim DBPatternMatch DeChunkText Declare Decrypt Degrees DeleteAttachment DeleteEmailAddress DeleteImage DeleteRecord DeleteRow DeleteSQL DeleteSystemPauseTimes DeQueue DetachAttachment DisableMenuItem DiscardRow DoCancel DoesTableExist DoModal DoModalComponent DoModalComponentPopup DoModalPanelGroup DoModalPopup DoModalX DoModalXComponent DoSave DoSaveNow DownloadToExcel
"     syn keyword pplBuiltinFunction Else EnableMenuItem EncodeSearchCode EncodeURL EncodeURLForQueryString Encrypt EncryptNodePswd EndMessage EndModal EndModalComponent End-While EnQueue Error EscapeHTML EscapeJavascriptString EscapeWML Evaluate Exact Exec ExecuteRolePeopleCode ExecuteRoleQuery ExecuteRoleWorkflowQuery ExecuteSearchSavePC Exit Exp ExpandBindVar ExpandEnvVar ExpandSqlBinds
"     syn keyword pplBuiltinFunction Fact FetchSQL FetchValue FieldChanged FileExists Find Findb FindCodeSetValues FindFiles FlushBulkInserts FormatDateTime Forward
"     syn keyword pplBuiltinFunction GenABNNodeURL GetComponentTitle GenDynABNElement GenerateActGuideContentUrl GenerateActGuidePortalUrl GenerateActGuideRelativeUrl GenerateComponentContentRelURL GenerateComponentContentURL GenerateComponentPortalRelURL GenerateComponentPortalURL GenerateComponentRelativeURL GenerateExternalPortalURL GenerateExternalRelativeURL GenerateHomepagePortalURL GenerateHomepageRelativeURL GenerateQueryContentURL GenerateQueryPortalURL GenerateQueryRelativeURL GenerateScriptContentRelURL GenerateScriptContentURL GenerateScriptPortalRelURL GenerateScriptPortalURL GenerateScriptRelativeURL GenerateTree GenerateWorklistPortalURL GenerateWorklistRelativeURL GenHTMLMenu GenToken GetABNChartRowSet GetABNInitialNode GetABNNode GetABNRelActnRowSet GetABNReqParameters GetABNTreeEffdt GetABNTreeName GetABNTreeSetid GetABNTreeUserKey GetAddSearchRecName GetAESection GetAnalyticGrid GetAnalyticInstance GetArchPubHeaderXmlDoc GetArchPubXmlDoc GetArchSubXmlDoc GetAttachment GetAttachmentURL GetBiDoc GetBreadcrumbs GetCalendarDate GetChart GetChartURL GetComponentTitle GetCwd GetDefinitionAccess GetDialGauge GetEnv GetField GetFile GetGanttChart GetGaugeThreshold GetGrid GetHTMLText GetImageExtents GetInterlink GetJavaClass GetLEDGauge GetLevel0 GetMethodNames GetMessage GetMessageInstance GetMessageXmlDoc GetNextNumber GetNextNumberWithGaps GetNextNumberWithGapsCommit GetNextProcessInstance GetNRXmlDoc GetOrgChart GetPage GetPageField GetPagePrefix GetPageTitle GetPageType GetPanelControlStyle GetProgramFunctionInfo GetPubContractInstance GetPubHeaderXmlDoc GetPubXmlDoc GetRatingBoxChart GetRatingGauge GetRatingGaugeState GetRecord GetReferenceArea GetReferenceLine GetRelField GetRow GetRowset GetRowsetCache GetSearchRecName GetSelectedTreeNode GetSeries GetSession GetSetId GetSparkChart GetSparkChartItem GetSQL GetStatusMeterGauge GetStoredFormat GetSubContractInstance GetSubXmlDoc GetSyncLogData GetTempFile GetThreshold GetToolTip GetTreeNodeParent GetTreeNodeRecordName GetTreeNodeValue GetURL GetUserOption GetWLFieldValue Global Gray GrayMenuItem GroupletRequestSource
"     syn keyword pplBuiltinFunction Hash HashSHA256 HashWithSalt HermiteCubic Hide HideMenuItem HideRow HideScroll HistVolatility Hour
"     syn keyword pplBuiltinFunction IBPurgeDomainStatus IBPurgeNodesDown Idiv If InboundPublishXmlDoc InitChat InsertImage InsertRow Int Integer IsAddEnabled IsAddMode IsAGComponent IsAGRequest IsAlpha IsAlphaNumeric IsBackEnabled IsClassicPlusMode IsDate IsDateTime IsDaylightSavings IsDigits IsFluidMode IsFluidSearchStart IsGroupletInteractive IsGroupletRequest IsHidden IsHomeEnabled IsIScriptAuthorized IsLogoutEnabled IsMDAJAXTrf IsMDComponent IsMDGuided IsMDListPopup IsMDListSlideout IsMDNonOptimized IsMDRequest IsMDSearchEnabled IsMenuItemAuthorized IsMessageActive IsModal IsModalComponent IsModalPanelGroup IsModeless IsNavBarEnabled IsNextInListEnabled IsNotificationEnabled IsNotifyEnabled IsNumber IsOperatorInClass ISOToDate ISOToDateTime IsPinEnabled IsPrevInListEnabled IsSaveEnabled IsSearchDialog IsSearchEnabled IsSingleComponentAG IsSingleUnitOfWork IsSmallFFOptimized IsStandardSearchEnabled IsTime IsUserInPermissionList IsUserInRole IsUserNumber
"     syn keyword pplBuiltinFunction Left Len Lenb LinearInterp Ln LoadABN Local LogObjectUse Log10 Lower LTrim
"     syn keyword pplBuiltinFunction MAddAttachment MarkPrimaryEmailAddress MarkWLItemWorked Max MCFBroadcast MessageBox Min Minute Mod Month MsgGet MsgGetExplainText MsgGetText
"     syn keyword pplBuiltinFunction NextEffDt NextRelEffDt NodeDelete NodeRename NodeSaveAs NodeTranDelete None Not NotifyQ NumberToDisplayString NumberToString
"     syn keyword pplBuiltinFunction ObjectDoMethod ObjectDoMethodArray ObjectGetProperty ObjectSetProperty OnlyOne OnlyOneOrNone Or OverrideCNAVDisplayMode OverrideConditionalNav
"     syn keyword pplBuiltinFunction PanelGroupChanged PingNode PriorEffDt PriorRelEffDt PriorValue Product Prompt Proper PublishXmlDoc PutAttachment Quote
"     syn keyword pplBuiltinFunction Radians Rand RecordChanged RecordDeleted RecordNew RefreshTree RelNodeTranDelete RemoteCall RemoveDirectory RenameDBField RenamePage RenameRecord Repeat Replace Rept ResizeImage ReSubmitPubHeaderXmlDoc ReSubmitPubXmlDoc ReSubmitSubXmlDoc Return Returns ReturnToServer ReValidateNRXmlDoc RevalidatePassword Right Round RoundCurrency RowFlush RowScrollSelect RowScrollSelectNew RTrim
"     syn keyword pplBuiltinFunction SamRefreshView ScheduleProcess ScrollFlush ScrollSelect ScrollSelectNew Second SecureRandomGen SendMail SetAddMode SetAuthenticationResult SetChannelStatus SetComponentChanged SetControlValue SetCursorPos SetDBFieldAuxFlag SetDBFieldCharDefn SetDBFieldFormat SetDBFieldFormatLength SetDBFieldLabel SetDBFieldLength SetDBFieldNotUsed SetDefault SetDefaultAll SetDefaultNext SetDefaultNextRel SetDefaultPrior SetDefaultPriorRel SetDisplayFormat SetLabel SetLanguage SetMDAJAXTrf SetMDGuided SetMDListPopup SetMDListSlideout SetMessageStatus SetNextPanel SetNextPage SetPageFieldPageFieldName SetPanelControlStyle SetPasswordExpired SetPostReport SetRecFieldEditTable SetRecFieldKey SetReEdit SetSaveWarningFilter SetSearchDefault SetSearchDialogBehavior SetSearchEdit SetTempTableInstance SetThemeId SetTracePC SetTraceSQL SetTransferAttributes SetupScheduleDefnItem SetUserOption ShareAttachment ShouldSuppressCREF Sign Sin SinglePaymentPV SortScroll Split SQLExec Sqrt StartWork Step StopFetching StoreSQL String StripOffHTMLTags Substitute Substring Substringb SwitchUser SyncRequestXmlDoc
"     syn keyword pplBuiltinFunction Tan Then throw Time Time3 TimePart TimeToTimeZone TimeValue TimeZoneOffset To TotalRowCount Transfer TransferExact TransferModeless TransferNode TransferPanel TransferPage TransferPortal TransferTop Transform TransformEx TransformExCache TreeDetailInNode TriggerBusinessEvent Truncate try
"     syn keyword pplBuiltinFunction UIDisplayMode UnCheckMenuItem Unencode Ungray Unhide UnhideRow UnhideScroll UniformSeriesPV UnshareAttachment Until UpdateSysVersion UpdateValue UpdateXmlDoc Upper
"     syn keyword pplBuiltinFunction Value ValueUser VerifyHash VerifyOprPassword ViewAttachment ViewContentURL ViewContentURLClassic ViewContentURLFluid ViewContentURLModeless ViewURL ViewURLModeless ViewURLTop
"     syn keyword pplBuiltinFunction Warning Weekday When When-Other While WinEscape WinExec WinMessage WriteToLog Year

function pplSystemVariables#setPplSystemVariables()
      syn match pplSystemVariable "%AllowNotification\%[\W\n]\@=\|%AllowRecipientLookup\%[\W\n]\@=\|%ApplicationLogFence\%[\W\n]\@=\|%AsOfDate\%[\W\n]\@=\|%AuthenticationToken\%[\W\n]\@=" 
      syn match pplSystemVariable "%BPName\%[\W\n]\@="
      syn match pplSystemVariable "%ClientDate\%[\W\n]\@=\|%ClientTimeZone\%[\W\n]\@=\|%Component\%[\W\n]\@=\|%CompIntfcName\%[\W\n]\@=\|%ContentID\%[\W\n]\@=\|%ContentType\%[\W\n]\@=\|%Copyright\%[\W\n]\@=\|%Currency\%[\W\n]\@="
      syn match pplSystemVariable "%DateTime\%[\W\n]\@=\|%Date\%[\W\n]\@=\|%DbName\%[\W\n]\@=\|%DbServerName\%[\W\n]\@=\|%DbType\%[\W\n]\@="
      syn match pplSystemVariable "%EmailAddress\%[\W\n]\@=\|%EmployeeId\%[\W\n]\@=\|%ExternalAuthInfo\%[\W\n]\@="
      syn match pplSystemVariable "%FilePath\%[\W\n]\@="
      syn match pplSystemVariable "%HPTabName\%[\W\n]\@="
      syn match pplSystemVariable "%IB_JSON\%[\W\n]\@=\|%IB_XML\%[\W\n]\@=\|%Import\%[\W\n]\@=\|%IntBroker\%[\W\n]\@=\|%IsMultiLanguageEnabled\%[\W\n]\@="
      syn match pplSystemVariable "%Language_Base\%[\W\n]\@=\|%Language_Data\%[\W\n]\@=\|%Language_User\%[\W\n]\@=\|%Language\%[\W\n]\@=\|%LocalNode\%[\W\n]\@="
      syn match pplSystemVariable "%MAP_Market\%[\W\n]\@=\|%Market\%[\W\n]\@=\|%MaxMessageSize\%[\W\n]\@=\|%MaxNbrSegments\%[\W\n]\@=\|%Menu\%[\W\n]\@=\|%Mode\%[\W\n]\@="
      syn match pplSystemVariable "%NavigatorHomePermissionList\%[\W\n]\@=\|%Node\%[\W\n]\@="
      syn match pplSystemVariable "%OperatorClass\%[\W\n]\@=\|%OperatorId\%[\W\n]\@=\|%OperatorRowLevelSecurityClass\%[\W\n]\@=\|%OutDestFormat\%[\W\n]\@=\|%OutDestType\%[\W\n]\@="
      syn match pplSystemVariable "%Page\%[\W\n]\@=\|%PanelGroup\%[\W\n]\@=\|%Panel\%[\W\n]\@=\|%PasswordExpired\%[\W\n]\@=\|%PerfTime\%[\W\n]\@=\|%PermissionLists\%[\W\n]\@=\|%PID\%[\W\n]\@=\|%Portal\%[\W\n]\@=\|%PrimaryPermissionList\%[\W\n]\@=\|%ProcessProfilePermissionList\%[\W\n]\@=\|%PSAuthResult\%[\W\n]\@="
      syn match pplSystemVariable "%Request\%[\W\n]\@=\|%Response\%[\W\n]\@=\|%ResultDocument\%[\W\n]\@=\|%Roles\%[\W\n]\@=\|%RowSecurityPermissionList\%[\W\n]\@=\|%RunningInPortal\%[\W\n]\@="
      syn match pplSystemVariable "%ServerTimeZone\%[\W\n]\@=\|%Session\%[\W\n]\@=\|%SignonUserId\%[\W\n]\@=\|%SignOnUserPswd\%[\W\n]\@=\|%SMTPBlackberryReplyTo\%[\W\n]\@=\|%SMTPGuaranteed\%[\W\n]\@=\|%SMTPSender\%[\W\n]\@=\|%SQLRows\%[\W\n]\@=\|%Super\%[\W\n]\@="
      syn match pplSystemVariable "%This\%[\W\n]\@=\|%Time\%[\W\n]\@=\|%ToolsRelease\%[\W\n]\@=\|%TransformData\%[\W\n]\@="
      syn match pplSystemVariable "%UserDescription\%[\W\n]\@=\|%UserId\%[\W\n]\@="
      syn match pplSystemVariable "%WLInstanceID\%[\W\n]\@=\|%WLName"
endfunction
